"""Milestone 8: Viva Defence Engine package."""

from backend.viva.models import (
    VivaDifficulty,
    VivaCategory,
    VivaRating,
    VivaGapSeverity,
    VivaDefenceReadiness,
    VivaSessionStatus,
    VivaSessionMode,
    VivaQuestion,
    VivaAnswerSubmission,
    VivaKnowledgeGap,
    VivaTurnEvaluation,
    CategoryMastery,
    VivaDefenceReport,
    VivaSessionRecord,
)
from backend.viva.exceptions import (
    VivaError,
    VivaSessionNotFoundError,
    TurnLimitExceededError,
    InvalidTurnProgressionError,
    ConcurrentSessionError,
    InsufficientEvidenceError,
)
from backend.viva.index import ProjectArchitecturalIndex
from backend.viva.generator import (
    generate_viva_question,
    DEFAULT_CATEGORY_CONCEPTS,
    build_question_generation_objective,
)
from backend.viva.evaluator import (
    evaluate_viva_answer,
    check_fast_path,
    escape_untrusted_text,
    student_noted_undocumented,
    build_viva_evaluation_objective,
)
from backend.viva.session import (
    start_viva_session,
    get_current_question,
    submit_viva_answer_and_step,
    get_session_state,
    promote_difficulty,
    demote_difficulty,
    recover_stale_session_if_needed,
    MAX_BASE_QUESTIONS,
    MAX_FOLLOWUP_PER_BASE,
    MAX_FOLLOWUPS_PER_SESSION,
    MAX_TOTAL_TURNS,
    STALE_RECOVERY_TIMEOUT_SECONDS,
)
from backend.viva.reporter import compile_viva_report

__all__ = [
    "VivaDifficulty",
    "VivaCategory",
    "VivaRating",
    "VivaGapSeverity",
    "VivaDefenceReadiness",
    "VivaSessionStatus",
    "VivaSessionMode",
    "VivaQuestion",
    "VivaAnswerSubmission",
    "VivaKnowledgeGap",
    "VivaTurnEvaluation",
    "CategoryMastery",
    "VivaDefenceReport",
    "VivaSessionRecord",
    "VivaError",
    "VivaSessionNotFoundError",
    "TurnLimitExceededError",
    "InvalidTurnProgressionError",
    "ConcurrentSessionError",
    "InsufficientEvidenceError",
    "ProjectArchitecturalIndex",
    "generate_viva_question",
    "DEFAULT_CATEGORY_CONCEPTS",
    "build_question_generation_objective",
    "evaluate_viva_answer",
    "check_fast_path",
    "escape_untrusted_text",
    "student_noted_undocumented",
    "build_viva_evaluation_objective",
    "start_viva_session",
    "get_current_question",
    "submit_viva_answer_and_step",
    "get_session_state",
    "promote_difficulty",
    "demote_difficulty",
    "recover_stale_session_if_needed",
    "MAX_BASE_QUESTIONS",
    "MAX_FOLLOWUP_PER_BASE",
    "MAX_FOLLOWUPS_PER_SESSION",
    "MAX_TOTAL_TURNS",
    "STALE_RECOVERY_TIMEOUT_SECONDS",
    "compile_viva_report",
]
