"""Terminal shell integration manager and script generation (Milestone 12.10).

This module handles:
1. Enabling, disabling, and checking terminal integration status.
2. Generating transparent shell wrappers (e.g., PowerShell profile scripts)
   that execute commands strictly once while capturing results into Build Coach.
3. Hook dispatcher for capturing and recording executions.
"""

from pathlib import Path
from typing import Optional, Dict, Any
from backend.domain.models import utc_now_iso
from backend.project_model.db import Database
from backend.terminal.protocol import (
    ShellType,
    IntegrationStatus,
    TerminalIntegrationStatus,
    TerminalCommandPayload,
)
from backend.terminal.session import TerminalSessionManager


POWERSHELL_PROFILE_TEMPLATE = """# AI Build Coach - Transparent Terminal Integration for PowerShell
# Auto-generated by: python -m backend.cli terminal enable {project_id}
# DO NOT EDIT DIRECTLY. Manage via: python -m backend.cli terminal [enable|disable|status]

$env:BUILDCOACH_PROJECT_ID = "{project_id}"
$env:BUILDCOACH_INTEGRATION = "1"

function Invoke-BuildCoachHook {{
    if (-not $args -or $args.Count -eq 0) {{
        return
    }}

    # Execute command strictly once via Build Coach terminal hook using underlying python executable
    $pyExe = (Get-Command python.exe -CommandType Application | Select-Object -ExpandProperty Source -First 1)
    if (-not $pyExe) {{ $pyExe = "python" }}
    & $pyExe -m backend.cli terminal hook "{project_id}" -- @args
    $global:LASTEXITCODE = $LASTEXITCODE
}}

# Transparent interception for pytest: developer runs 'pytest ...' normally
function pytest {{
    Invoke-BuildCoachHook "pytest" @args
}}

# Transparent interception for python: developer runs 'python ...' normally
# If invoked without arguments or interactive, passes through directly to avoid REPL interception
function python {{
    if (-not $args -or $args.Count -eq 0) {{
        & (Get-Command python.exe -CommandType Application | Select-Object -First 1)
    }} else {{
        Invoke-BuildCoachHook "python" @args
    }}
}}

# General helper alias
Set-Alias -Name bc-run -Value Invoke-BuildCoachHook -Scope Global -Option AllScope

Write-Host " [Build Coach] Terminal integration active for project: {project_name} ({project_id})" -ForegroundColor Cyan
Write-Host "               Normal commands ('pytest', 'python <args>', 'bc-run <cmd>') are tracked automatically." -ForegroundColor Gray
"""


class TerminalIntegrationManager:
    """Manages shell integration configuration, scripts, and status for projects."""

    def __init__(self, db: Database, session_manager: Optional[TerminalSessionManager] = None):
        self.db = db
        self.session_manager = session_manager or TerminalSessionManager(db)

    def enable(
        self,
        project_id: str,
        shell_type: str = ShellType.POWERSHELL.value,
        config: Optional[Dict[str, Any]] = None,
    ) -> TerminalIntegrationStatus:
        """Enables terminal integration for a project and generates shell scripts."""
        project = self.db.get_project_by_id(project_id)
        if not project:
            raise ValueError(f"Project '{project_id}' is not registered in Build Coach.")

        root_path = Path(project.root_path)
        term_dir = root_path / ".buildcoach" / "terminal"
        term_dir.mkdir(parents=True, exist_ok=True)

        hook_script_path: Optional[str] = None
        clean_shell = shell_type.lower()
        if clean_shell in (ShellType.POWERSHELL.value, "pwsh"):
            ps_script = term_dir / "buildcoach.ps1"
            script_content = POWERSHELL_PROFILE_TEMPLATE.format(
                project_id=project_id,
                project_name=project.name,
            )
            ps_script.write_text(script_content, encoding="utf-8")
            hook_script_path = str(ps_script)

        now = utc_now_iso()
        self.db.upsert_terminal_integration(
            project_id=project_id,
            status=IntegrationStatus.ENABLED.value,
            shell_type=clean_shell,
            script_path=hook_script_path,
            enabled_at=now,
        )

        return TerminalIntegrationStatus(
            project_id=project_id,
            status=IntegrationStatus.ENABLED.value,
            shell_type=clean_shell,
            hook_script_path=hook_script_path,
            enabled_at=now,
        )

    def disable(self, project_id: str) -> TerminalIntegrationStatus:
        """Disables terminal integration for a project."""
        project = self.db.get_project_by_id(project_id)
        if not project:
            raise ValueError(f"Project '{project_id}' is not registered in Build Coach.")

        existing = self.db.get_terminal_integration(project_id)
        shell_type = existing.get("shell_type", ShellType.POWERSHELL.value) if existing else ShellType.POWERSHELL.value
        hook_script_path = existing.get("script_path") if existing else None

        now = utc_now_iso()
        self.db.upsert_terminal_integration(
            project_id=project_id,
            status=IntegrationStatus.DISABLED.value,
            shell_type=shell_type,
            script_path=hook_script_path,
            enabled_at=existing.get("enabled_at") if existing else None,
            disabled_at=now,
        )

        return TerminalIntegrationStatus(
            project_id=project_id,
            status=IntegrationStatus.DISABLED.value,
            shell_type=shell_type,
            hook_script_path=hook_script_path,
            enabled_at=existing.get("enabled_at") if existing else None,
            disabled_at=now,
        )

    def get_status(self, project_id: str) -> TerminalIntegrationStatus:
        """Retrieves terminal integration status for a project."""
        project = self.db.get_project_by_id(project_id)
        if not project:
            raise ValueError(f"Project '{project_id}' is not registered in Build Coach.")

        existing = self.db.get_terminal_integration(project_id)
        if not existing:
            return TerminalIntegrationStatus(
                project_id=project_id,
                status=IntegrationStatus.DISABLED.value,
                shell_type=ShellType.POWERSHELL.value,
                hook_script_path=None,
                enabled_at=None,
            )

        st = existing.get("status", IntegrationStatus.DISABLED.value)
        shell_str = existing.get("shell_type", ShellType.POWERSHELL.value)

        return TerminalIntegrationStatus(
            project_id=project_id,
            status=st,
            shell_type=shell_str,
            hook_script_path=existing.get("script_path"),
            enabled_at=existing.get("enabled_at"),
            disabled_at=existing.get("disabled_at"),
        )
